### ISSUE TITLE
overall episode organization

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/organization-geospatial#1]
Based on the CAC discussion, this repo is intended as a non-coding dependent introduction to geospatial data formats and project organization. This lesson will be taught before any R has been covered, and so must not require the learner to know any R. R code can be used in the lessons to create graphics / maps, but the learner should not have to interact with the R code. 

Episode 1: Spatial data formats
 - file types
 - vector file types, what is a shapefile, what is a geojson object
 - raster file types
 - geospatial databases?
 - geographic and projected coordinate systems - what they are, why they matter, how to select them

Episode 2: Project organization and management
 - some from https://github.com/datacarpentry/r-spatial-data-management-intro/blob/master/_episodes_rmd/02-spatial-data-formats.Rmd

Episode 3: Spatial data landscape

This information is already (at least mostly) in this repo, but needs to be reorganized to fit this episode structure. 

Note: although in other Data Carpentry lessons, data cleaning is often part of the initial lesson, it will not be included in this lesson as data structures for geospatial data are complicated and may be intimidating to learners to see at the very beginning of the workshop. Data cleaning should be integrated into the rest of the lessons.

**Comment by ErinBecker** [comment]
More information about the CAC's discussion of this reorganization can be found 

[In the CAC meeting minutes](https://github.com/datacarpentry/curriculum-advisors/blob/master/geospatial/minutes/march-2018-geospatial-minutes.md)

**Comment by ErinBecker** [comment]
@obrl-soil - please note that this repository is a copy of the old [Introduction to spatio-temporal data repo](https://github.com/datacarpentry/organization-geospatial-DEPRECATED). It needs major reorganization (removal of entire episodes, moving parts from one episode to another, etc). Please make a fork before major rearrangement, but don't be afraid to slice and dice!

**Comment by obrl-soil** [comment]
Thanks @ErinBecker - I'm pencilling in some time on the weekend :)

**Comment by ErinBecker** [comment]
Hey @obrl-soil - have you been able to take a stab at this reorganization? With the Bug BBQ starting tomorrow, I'd like to have a fresh repo reorganization available for them if possible. I can take a crack at moving things around tomorrow morning, but I don't know anything about geospatial data, so I would probably break something. Please let me know if you'll be able to do some reorg before the Bug BBQ.

**Comment by obrl-soil** [comment]
HI @ErinBecker yes I've got some draft material so far at my forked repo, but I want to add more before I PR it. CRS and metadata content needs more work.

**Comment by ErinBecker** [comment]
Great to hear the work is coming along! I'd highly recommend putting in a PR with your materials (even if they're not done) before the Bug BBQ starts tomorrow morning. There will be a sizable cohort of people working on these lessons during the Bug BBQ and it would be nice to avoid a big snarly merge conflict right out the gate. Please let me know if there's anything I can help with.

**Comment by obrl-soil** [comment]
Cool cool, first PR is in. Might be able to write more tonight (now + 9 hours or so).

**Comment by obrl-soil** [comment]
@ErinBecker I think lessons 2 and 3 need to be swapped - currently its jarring to go from 'what is spatial data' to 'how to make an rstudio project' back to 'what is a GIS'. 1-3-2 seems like a more logical progression. What do you think?

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/organization-geospatial/pull/34
