### ISSUE TITLE
comments from the pros to callout box

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/organization-geospatial#13]
In [this episode](http://www.datacarpentry.org/organization-geospatial/01-spatial-data-structures-formats/), this text:

>> Comments from the pros: Take the time to figure identify a projection that is suited for your project. You don’t have to stick to the ones that are popular.

Should be in a callout box.

**Comment by annefou** [comment]
I am taking this issue to start working in this lesson...

**Comment by r4space** [comment]
Thanks @annefou!
