### ISSUE TITLE
"needs more"? unclear

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/organization-geospatial#14]
In [this episode](http://www.datacarpentry.org/organization-geospatial/01-spatial-data-structures-formats/), there is a "needs more" comment after the "PROJ" header. It's not clear whether that means there should be more information about the PROJ format, or if there should be more formats listed after the PROJ section.

**Comment by obrl-soil** [comment]
This was resolved with PR [#20](https://github.com/datacarpentry/organization-geospatial/pull/20).
