### ISSUE TITLE
recommend removing discussion of Python

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/organization-geospatial#25]
Since all of the coding lessons in this workshop are currently based on R, I would recommend removing the section of [the third episode](http://www.datacarpentry.org/organization-geospatial/aio.html) that discusses Python packages and just focus on R. 

Inclusion of Python risks cognitive load issues.

**Comment by obrl-soil** [comment]
Have to say I'm not sure this workshop fits in too well with the other two at all - most of what's in here feels like pre-reading, or maybe 'read-more' material that could supplement r-intro-geospatial and raster-vector-geospatial.

**Comment by ErinBecker** [comment]
I agree that it's supplementary. The idea is that this lesson will only be taught if the audience is not already familiar with geospatial concepts. The paragraph below from the [workshop homepage](https://datacarpentry.org/geospatial-workshop/) tries to set that expectation. What do you think?

>> This workshop assumes no prior experience with the tools covered in the workshop. However, learners with prior experience working with geospatial data may be able to skip the Geospatial Project Organization and Management lesson. Similarly, learners who have prior experience with the R programming language may wish to skip the Introduction to R for Geospatial Data lesson.

**Comment by obrl-soil** [comment]
Yep works for me
