### ISSUE TITLE
Add info in Readme.md about compiling lesson

### ISSUE THREAD

**Issue by jebyrnes** [datacarpentry/organization-geospatial#42]
For those of us who want to modify and check how things work, can you add info to the readme.md - even just a link - on how to test compilation on our own computers. Some of us are old hands at individual markdown documents, but lack experience in this larger workflow.  

Hrm. Oughta be a DC lesson on that....or some pages? (been looking around, but haven't found it)

**Comment by jsta** [comment]
Nice idea, in the mean-time the necessary system setup is described [here](https://carpentries.github.io/lesson-example/setup.html#optional-jekyll-setup-for-lesson-development) and the build process starts by running `make serve` in a terminal and viewing your `localhost` in a browser.

**Comment by jsta** [comment]
Looks like this info is in the README at https://github.com/datacarpentry/r-raster-vector-geospatial and could be ported over.
