### ISSUE TITLE
Broken links in  _episodes_rmd/03-crs.Rmd 

### ISSUE THREAD

**Issue by Astahlke** [datacarpentry/organization-geospatial#57]
Under **Which projection should I use** of Episode 3: Coordinate Reference Systems
 Line 113 references a two broken links:

- [University of Colorado's Map Projections](https://www.colorado.edu/geography/gcraft/notes/mapproj/mapproj_f.html)
- [Department of Geo-Information Processing](http://kartoweb.itc.nl/geometrics/map%20projections/mappro.html)

I'm guessing these should be:
- https://foote.geography.uconn.edu/gcraft/notes/mapproj/mapproj_f.html and
- https://kartoweb.itc.nl/geometrics/Map%20projections/mappro.html

Thanks for this lesson!

**Comment by jsta** [comment]
Thanks! I created a Pull Request at #58 with a fix to this.
