### ISSUE TITLE
Lesson Contribution - Two suggestions on Episode 3 and 4

### ISSUE THREAD

**Issue by Talishask** [datacarpentry/organization-geospatial#72]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.
---

On https://datacarpentry.org/organization-geospatial/04-geo-landscape/index.html
My comment is that the addition of the software package ENVI by L3Harris is widely used for Remote Sensing and should be included. It is heavily used in the community.

The other comment is very minor but on https://datacarpentry.org/organization-geospatial/03-crs/index.html

It would be helpful to distinguish the difference between a geographic coordinate system and the projected systems. It comes up, especially when dealing with measurements and distance.

**Comment by srappel** [comment]
These both seem sensible.

@jhollist should we bring these up at the CAC meeting? 

Any maintainers have thoughts on these?

**Comment by jsta** [comment]
My slight preference would be to not list any commercial software.

**Comment by srappel** [comment]
@jsta There is a whole section on the page for commercial software. I think it's worth a discussion on how exhaustive the "landscape" list is and what makes something worth listing.

**Comment by jhollist** [comment]
@srappel all of these are certainly a good fit for the CAC.   Projections, CRS, etc. will definitely be a topic given all the changes the PROJ and the supporting geospatial packages.

**Comment by misgna3** [comment]
Both suggestions are acceptable. In fact, categorizing the list into software that are GIS emphasis (such as ArcGIS, QGIS, Manifold) & Remote sensing or image analysis emphasis (such as ERDAS, ENVI, IDRISI) or adding notes to that effect may be a good idea.
