### ISSUE TITLE
add image to illustrate OGC Simple Features

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/organization-geospatial#8]
[Episode 1](http://www.datacarpentry.org/organization-geospatial/01-spatial-data-structures-formats/) includes the text:

>> Vector data structures aim to represent specific features on the Earth’s surface, and then assign attributes to those features. All vector datasets are based around coordinate points - usually paired x,y values in 2D space. There are many possible way to arrange and connect a set of points, so some standards have been developed to keep vector formats interoperable. The most common standard you will encounter is OGC Simple Features.

>> Simple Features defines 17 types of vector geometry, and the vast majority of data uses just three of these classes - Points, Lines, and Polygons. Points are assembled into more complex structures by straight lines only.

There is then a place to insert an image. Anyone have an image to illustrate this concept?

**Comment by pmarchand1** [comment]
The sf vignette (https://cran.r-project.org/web/packages/sf/vignettes/sf1.html) lists 7 common ones (Point, Line, Polygon, the "multi" version of those 3, and GeometryCollection) and 10 less common types, many of them including curved lines.

A possible illustration could be based on country maps. Points for locations of cities, multilines for boundaries taken as lines, polygons for the country area, and multipolygon for some countries e.g. archipelagos.

**Comment by r4space** [comment]
I'm coming to the conversation super late so apologies if this has all already been hashed out.  

+1 for the map based illustration!  

What do people think of using the formal illustrations just from [OGC ](http://www.opengeospatial.org/standards/sfa)for intro and a map for summary?

There's a simple example of the OGC illustrations just colourised [here](http://www.maths.lancs.ac.uk/~rowlings/Teaching/OSgeo/Nov2008/Technology/slide21.html)

**Comment by ErinBecker** [comment]
I'm in favor of repurposing existing illustrations wherever possible. @r4space - do you know the licensing information on that image?

**Comment by blordcastillo** [comment]
New reference after reorganization is at [Intro to Vector Data L37](https://github.com/datacarpentry/organization-geospatial/blob/master/_episodes_rmd/02-intro-vector-data.Rmd#L37).  
  
Since the language on vector standards (as well as more complex vector objects) has been dropped, the existing illustration there now is probably all that is needed.

**Comment by jsta** [comment]
Agreed. Happy to re-open if there is disagreement.
