### ISSUE TITLE
replace rgdal and rgeos with equivalent calls from sf or terra

### ISSUE THREAD

**Issue by zkamvar** [datacarpentry/organization-geospatial#88]
### What is the problem?

The introduction episode along with several files in the `code/` folder (which is unused in the lesson) still have `library(rgdal)`, which is now causing the lesson to fail building due to the fact that the {rgdal} package is now retired.

This was opened in the r-raster-vector-geospatial lesson in 2021: https://github.com/datacarpentry/r-raster-vector-geospatial/issues/363 and the @datacarpentry/curriculum-advisors-geospatial had [made a recommendation to replace rgdal and rgeos with calls from sf or terra](https://github.com/datacarpentry/curriculum-advisors/blob/main/geospatial/2022Q1_Geospatial_CAC_Minutes.md):

> * Deprecation of the sp, rgeos, and rgdal packages
>   
>   * The Committee agreed that the references to rgdal and rgeos be removed or replaced with references to the equivalent sf and terra functions as appropriate. This decision is closely paired with the rationale for choosing terra as the replacement for the raster package and aims to avoid code-breaking deprecations coming some time in 2023.
> * Transition from raster to terra or stars
>   
>   * The terra package appears to be the most direct replacement for raster as it uses language which is similar to raster and common to other GIS. The Committee recommends that terra be adopted as a replacement to raster. Stars should be presented as an alternative to terra that may be faster in some cases or more appropriate for analyses with longitudinal elements.

### Location of problem (optional)

https://github.com/search?q=repo%3Adatacarpentry%2Forganization-geospatial+%28rgdal+OR+rgeos%29&type=code

**Comment by jonjab** [comment]
I can take care of this. I forked this afternoon.
Before I can work tho: the paths to the data are all weird. 
also: how come I can't claim this issue?

**Comment by zkamvar** [comment]
> Before I can work tho: the paths to the data are all weird.

Are you referring to the fact that the data are not stored in the main branch of the repository? They are sourced from this file at the beginning: https://github.com/datacarpentry/organization-geospatial/blob/main/episodes/files/setup.R

**Comment by tobyhodges** [comment]
Thanks very much, both. @jonjab I have assigned the issue to you now.
