### ISSUE TITLE
mention of arc-node topology

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/organization-geospatial#9]
[This episode](http://www.datacarpentry.org/organization-geospatial/01-spatial-data-structures-formats/) has the following note. I'm adding it here and removing from the episode itself. The question is, should arc-node topology be mentioned at the end of the vector section of this episode or in the [raster vector](https://github.com/datacarpentry/r-raster-vector-geospatial/) lesson instead?

>> <worth mentioning arc-node topology yet? probs leave until specific vector lesson>

**Comment by annefou** [comment]
I would not mention it in [this episode](http://www.datacarpentry.org/organization-geospatial/01-spatial-data-structures-formats/) but in the [raster vector lesson](https://github.com/datacarpentry/r-raster-vector-geospatial/) instead.

**Comment by r4space** [comment]
Note was left in lesson, submitted a PR that just removes it.

+1 for leaving it for a later lesson not 01
