### ISSUE TITLE
Remove the `code` directory?

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/organization-geospatial#93]
### How could the content be improved?

Does the `code` directory still need to be in this lesson repository? As noted by @jonjab in #92, the files there seem to include some code that is no longer aligned with the content of the lesson. I wonder if there is any benefit to continuing to include the directory here at all?

Any thoughts @datacarpentry/organization-geospatial-maintainers @datacarpentry/curriculum-advisors-geospatial?

### Which part of the content does your suggestion apply to?

https://github.com/datacarpentry/organization-geospatial/tree/main/code/R/dc-spatio-temporal-intro

**Comment by HaoZeke** [comment]
Makes sense to me, AFAIK they aren't in use (and can be restored if anything goes wrong).

**Comment by jonjab** [comment]
In the PR for #88, I have now removed that directory.

The renv is still blowing up tho.

**Comment by tobyhodges** [comment]
This was addressed by @jonjab in #88
